### ISSUE TITLE
AsyncLock.withLock does not lock

### ISSUE THREAD

**Issue by groue** [mattmassicotte/Lock#1]
[`AsyncLock.withLock`](https://github.com/mattmassicotte/Lock/blob/0.1.0/Sources/Lock/AsyncLock.swift#L56) does not call `lock()` 😉

**Comment by mattmassicotte** [comment]
Is that bad?

**Comment by mattmassicotte** [comment]
fixed with 8bb7901a98ce14fcdedbe266905ca3300bde4f82
